name: Run Streamlit App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "GOOGLE_SHEETS_CREDENTIALS=${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" >> $GITHUB_ENV

    - name: Run Streamlit app
      run: |
        streamlit run app.py
